---
name: Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push (base)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./base/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:base

    - name: Build and push (builder)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./builder/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:builder

    - name: Build and push (latex-base)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./latex-base/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:latex-base

    - name: Build and push (latex-builder)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./latex-builder/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:latex-builder

    - name: Build and push (scipy-builder)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./scipy-builder/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:scipy-builder

    - name: Build and push (scipy-latex-builder)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./scipy-latex-builder/Dockerfile
        platforms: linux/amd64
        push: true
        tags: biggates/docker-sphinx-latex-cn:scipy-latex-builder
